'1_1_14_14_1024_1024_1_1_1_1_1': 1
'1_1_14_14_1024_512_1_1_1_1_1': 5
'1_1_14_14_512_1024_1_1_1_1_1': 6
'1_1_14_14_512_1024_1_2_2_1_1': 1
'1_1_1_1_2048_1000_1_1_1_1_1': 1
'1_1_28_28_256_512_1_1_1_1_1': 4
'1_1_28_28_256_512_1_2_2_1_1': 1
'1_1_28_28_512_256_1_1_1_1_1': 3
'1_1_28_28_512_512_1_1_1_1_1': 1
'1_1_56_56_128_256_1_1_1_1_1': 3
'1_1_56_56_256_128_1_1_1_1_1': 2
'1_1_56_56_256_256_1_1_1_1_1': 1
'1_1_56_56_64_128_1_1_1_1_1': 1
'1_1_56_56_64_256_1_1_1_1_1': 1
'1_1_7_7_1024_2048_1_1_1_1_1': 3
'1_1_7_7_1024_2048_1_2_2_1_1': 1
'1_1_7_7_2048_1024_1_1_1_1_1': 2
'3_3_14_14_16_512_1_1_1_1_1': 5
'3_3_14_14_16_512_1_2_2_1_1': 1
'3_3_28_28_8_256_1_1_1_1_1': 3
'3_3_28_28_8_256_1_2_2_1_1': 1
'3_3_56_56_4_128_1_1_1_1_1': 3
'3_3_7_7_32_1024_1_1_1_1_1': 2
'3_3_7_7_32_1024_1_2_2_1_1': 1
'7_7_112_112_3_64_1_2_2_1_1': 1
